Agrega relato sobre el salario mínimo
nepito/bukeh_example pull request #3
Opened 2022-02-11 06:10 UTC by davidmacer

Aquí agrego el escrito hecho por el Paco sobre el salario mínimo para pegarle una chainiadita.

2022-02-15 05:27 UTC, nepito requested changes
@davidmacer aquí te dejo algunos cambios. Básicamente es para agregar algunas cosas que de fueron de [Bootstrap](https://getbootstrap.com/docs/5.1/getting-started/introduction/). Yo lo único que he revisado este [video](https://youtu.be/qgxhrJFTOJs) del 🍆 ese.

2022-02-15 05:27 UTC, nepito commented on myapp/template.html
> +    <script src="https://cdn.bokeh.org/bokeh/release/bokeh-2.4.2.min.js"></script>
Esto lo ocupamos para poder "renderizar" bonito el texto:
```suggestion
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.bokeh.org/bokeh/release/bokeh-2.4.2.min.js"></script>
```

2022-02-15 05:27 UTC, nepito commented on myapp/template.html
> +    <script src="https://cdn.bokeh.org/bokeh/release/bokeh-mathjax-2.4.2.min.js"></script>
Este es otro que también ocupamos. La verdad no estoy seguro de cuál de los dos:
```suggestion
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.bokeh.org/bokeh/release/bokeh-mathjax-2.4.2.min.js"></script>
```

2022-02-15 05:27 UTC, nepito commented on myapp/template.html
> +    <div>
Con este cambio haces que no ocupe toda la pantalla. Deja unos márgenes
```suggestion
    <div  class="container">
```

2022-02-15 05:27 UTC, nepito commented on myapp/template.html
> +        <p>
Con esto cambiamos un poco el tipo de letra:
```suggestion
        <p  class="lead">
```

2022-02-15 05:27 UTC, nepito commented on myapp/template.html
> +    <div>
Aquí hay dos cambios. El primero es para que no se vaya a ocupar toda la pantalla y  el segundo para no agregar alguna característica especial a la figura (pero la neta no sé cuál es esa característica):
```suggestion
    <div class="container">
        <figure class="figure">
```

2022-02-15 05:27 UTC, nepito commented on myapp/template.html
> +    </div>
Aquí usamos la característica de bootstrap para hacer pie de figuras:
```suggestion
        <figcaption class="figure-caption text-end"><strong>Figura 1.</strong> Ingreso mensual en México en función de los años de estudio.</figcaption>
    </figure>
	    </div>
```

2022-02-15 05:31 UTC, nepito requested changes

2022-02-15 05:31 UTC, nepito commented on myapp/template.html
> +            Salarios mínimos en México
Lo voy a tratar de poner como título
```suggestion
            <h2>Salarios mínimos en México</h2>
```

2022-02-16 04:10 UTC, davidmacer commented
@nepito, consigné las sugerencias que pusiste porque ya las tenías y al parecer estaban jalando bien. Por ahí la regué al momento de hacer el merge y no puse atención sobre cuál archivo era el bueno. Está de tu lado de nuevo a ver qué te parece.

2022-02-16 04:45 UTC, davidmacer commented
@nepito, está toda madre ver la gráfica interactiva que pone los números jeje, pero estaría a toda madre poder ver el relato con el salario mínimo y la gráfica donde estás teniendo problemas con el _hoover_. ¿Cómo hago para ver eso?

2022-07-13 23:40 UTC, closed without merging